server:
  port: 8080

opennms:
  home: ${OPENNMS_HOME:/opt/minion}
  instance:
    id: ${OPENNMS_INSTANCE_ID:OpenNMS}
  minion:
    id: ${MINION_ID:minion-default-01}
    location: ${MINION_LOCATION:Default}
    gateway:
      host: ${MINION_GATEWAY_HOST:envoy}
      port: ${MINION_GATEWAY_PORT:8443}
    rpc.enabled: true
    sink.enabled: true
    twin.enabled: true
    snmp.enabled: true
    icmp.enabled: true
    traps.enabled: true
    syslog.enabled: true
    poller.enabled: true
    collector.enabled: true
    detector.enabled: true
    telemetry:
      enabled: true
      port: 4729
      address: "*"
      queue-size: 10000
      num-threads: 2
    heartbeat.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,detectors,monitors,collectors,prometheus
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: opennms-minion
